# Generated by Django 2.0.2 on 2018-02-10 03:21

import cryptography.hazmat.backends
from django.db import migrations, models
import django.db.models.deletion
import rsakeys.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSAKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', rsakeys.fields.RSAKeyField(backend=cryptography.hazmat.backends.default_backend, key_size=2048, public_exponent=65537)),
                ('private_pem', models.BinaryField(blank=True, null=True)),
                ('public_pem', models.BinaryField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rsa_keys', to='accounts.User')),
            ],
        ),
    ]
